sudo: required
services:
  - docker

before_install:
  - docker build -t mbmclaugh6/docker-react-tutorial -f Dockerfile.dev .

script:
  - docker run mbmclaugh6/docker-react-tutorial npm run test -- --coverage